/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cooltrickshome_RemapKeys */

#ifndef _Included_com_cooltrickshome_RemapKeys
#define _Included_com_cooltrickshome_RemapKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cooltrickshome_RemapKeys
 * Method:    remapPassedKeys
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_cooltrickshome_RemapKeys_remapPassedKeys
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

